<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- CSRF Token -->
	<meta name="csrf-token" content="{{ csrf_token() }}">

	<title>Angono Baranggay Services</title>

	<!-- Scripts -->
	<script src="{{ asset('js/landing.js') }}" defer></script>
	<script src="{{ asset('js/manifest.js') }}" defer></script>
	<script src="{{ asset('js/vendor.js') }}" defer></script>
	<script src="{{ asset('js/app.js') }}" defer></script>

	<!-- Fonts -->
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

	<!-- Styles -->
	<link href="{{ asset('css/app.css') }}" rel="stylesheet">
	<link href="{{ asset('css/landing.css') }}" rel="stylesheet">
</head>
<body>
	<div class="container mx-auto" style="color: #374151;">
		<!-- <img src="{{ asset('img/angono-file-header.png') }}"> -->
		<p class="text-sm" style="margin-top: .25rem;">Report for {{ $report }} {{ $report == 'appointments' ? 'between '.$from.' - '.$to : '' }}</p>
		<p class="text-sm" style="margin-top: .25rem;">Generated on {{ date_format(now(), 'jS F Y') }}</p>
		<p class="text-sm" style="margin-top: .25rem;">Generated by {{ $user->first_name }}</p>
		<!-- <h1 class="text-3xl text-center mb-2 mt-0" style="color: #ef4444; margin-top: 0px;">{{-- $service->name --}}</h1> -->
		<!-- <p class="mb-2">Please fill in your details prior to submitting this form on your appointed date.</p> -->
		<table class="min-w-full divide-y divide-gray-200" style="margin-top: 2rem;">
			<thead>
				<tr>
					@foreach($headers as $header)
					<th class="text-left">{{ $header }}</th>
					@endforeach
				</tr>
			</thead>
			<tbody>
				@if($report == 'appointments')
					@forelse($model as $data)
						<tr>
							<td class="text-sm">{{ $data->service->name }}</td>
							<td class="text-sm">{{ $data->user->name }} {{ $data->user->surname }}</td>
							<td class="text-sm">{{ date('Y-m-d', strtotime($data->slot->date)) }}</td>
							@if($data->status == 'Cancel')
								<td class="text-sm">Cancelled</td>
							@else
								<td class="text-sm">{{ $data->status }}</td>
							@endif
						</tr>
					@empty

					@endforelse
				@else
					@forelse($model as $data)
						<tr>
							<td class="text-sm">{{ $data->name }}</td>
						</tr>
					@empty

					@endforelse
				@endif
			</tbody>
		</table>
		<!-- <img src="{{ asset('img/angono-file-footer.png') }}"> -->
	</div>
</body>
</html>